### ISSUE TITLE
Course not displaying at legacy site

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/course_chem104#1]
The course does not appear to display on the legacy homepage, although there appears to be a blank line "reserved" for it after CHEM103. The URL structure `https://legacy.saylor.org/chem104/Intro/` returns a 404.

Syllabus can be seen here:
http://www.saylor.org/site/syllabus.php?cid=28

**Comment by athuggins** [comment]
The front matter was removed for some reason. Fixed.
